use fantavoto_ai

CREATE TABLE player_stats (
Matchweek int NOT NULL,
ID int NOT NULL,
Name varchar(255),
Position varchar(255),
Minutes int,
Goals int,
Assists int,
Pens int,
Pens_attempted int,
Shots int,
Shots_on_target int,
Yellow_card int,
Red_card int,
Touches int,
Tackles int,
Intercepts int,
Blocks int,
XG float,
NPXG float,
XA float,
SCA float,
GCA float,
Pass_completed int,
Pass_attempted int,
Progressive_pass int,
Carries int,
Progressive_carries int,
Dribbles int,
Dribbles_attempted int,
Pen_scored int,
Pen_failed int,
Own_goals int,
GK_sota int,
GK_GA int,
GK_saves int,
GK_PSXG int,
GK_launches_completed int,
GK_passes int,
GK_throws int,
GK_avg_pass_length int,
GK_crosses int,
GK_crosses_stopped int,
GK_def_actions_outside_box int,
GK_avg_distance_def_actions float,
GK_pen_saved int,
Mark float,
FantaPosition char,
MatchStatsRef varchar(255),
Team char
);

ALTER TABLE player_stats ADD UNIQUE player_stats_index (`Matchweek`, `ID`);

CREATE TABLE players (
ID int NOT NULL UNIQUE,
Position char NOT NULL,
Name varchar(255) NOT NULL,
Surname varchar(255) NOT NULL
);

CREATE TABLE match_stats (
MatchID varchar(255) NOT NULL UNIQUE,
Home_team varchar(255),
Home_goal int,
Home_xg float,
Home_possession int,
Home_pass_accuracy int,
Home_sota int,
Home_saves int,
Home_fouls int,
Home_corners int,
Home_crosses int,
Home_tackles int,
Home_interceptions int,
Home_clearances int,
Home_offsides int,
Away_team varchar(255),
Away_goal int,
Away_xg float,
Away_possession int,
Away_pass_accuracy int,
Away_sota int,
Away_saves int,
Away_fouls int,
Away_corners int,
Away_crosses int,
Away_tackles int,
Away_interceptions int,
Away_clearances int,
Away_offsides int
);
