title: FantaWomen VotoAI
description: Optimising a ML algorithm to estimate to evaluate performances of players from Serie A Women using open-data!
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-spaceship